version: '2'
services:
  db:
    image: postgres:latest
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  app:
    build: .
    depends_on:
      - "db"    
    ports:
      - "8050:8050"